# Generated by Django 5.1.4 on 2024-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("univeristy", "0012_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagePrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.CharField(
                        help_text="Enter text to generate an image.", max_length=255
                    ),
                ),
                (
                    "generated_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="generated_images/"
                    ),
                ),
            ],
        ),
    ]
