# Generated by Django 5.0.4 on 2024-09-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("univeristy", "0008_sponsor_eventsponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
