# Generated by Django 5.0.4 on 2024-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("univeristy", "0009_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="player_images/"),
        ),
    ]
